version: '3'
services:
  backend:
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - database
  database:
    image: mongo
    volumes:
      - /data/db
    ports:
      - '27017:27017'
